(defun xcpu-commit-current-file ()
  (interactive)
  (magit-stage-file (magit-file-relative-name))
  (magit-commit)
  )

(global-set-key (kbd "C-, c") 'comment-region)
(global-set-key (kbd "C-, u") 'uncomment-region)
(global-set-key (kbd "C-, w") 'delete-trailing-whitespace)
(global-set-key (kbd "C-, r") 'revert-buffer)
(global-set-key (kbd "C-, K") 'kill-rectangle)
(global-set-key (kbd "C-, e") 'eval-region)
(global-set-key (kbd "C-, a") 'align-regexp)
(global-set-key (kbd "C-, s") 'delete-trailing-whitespace)
(global-set-key (kbd "C-, c") 'xcpu-commit-current-file)
(global-set-key (kbd "C-, C") 'blog-insert-cve-markdown-link)
(global-set-key (kbd "C-, D") 'blog-insert-debian-bts-markdown-link)
